#!/bin/bash

if [ -z "$1" ]; then
    echo "No 'objdump' (nor any variant of) given."
    exit 1
fi

if [ -z "$2" ]; then
    echo "No program to disassemble given."
    exit 1
fi

"$1" -d "$2" -M intel -C -l -j .text --no-show-raw-insn | perl -pe 's/^ +[0-9a-z]+//g' | perl -pe 's/^://g'
