#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Please give: full path to appropriate objdump, executable name." 1>&2
    exit 1
fi

ls "$1" 1>/dev/null 2>/dev/null
if [ $? -ne 0 ]; then
    echo "Given a non-existent 'objdump'." 1>&2
    exit 1
fi

ls "$2" 1>/dev/null 2>/dev/null
if [ $? -ne 0 ]; then
    echo "Given a non-existent executable." 1>&2
    exit 1
fi

"$1" -d "$2" -M intel -C -l -j .text --no-show-raw-insn | perl -pe 's/^ +[0-9a-z]+//g' | perl -pe 's/^://g'
