#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Please give: file name, partition number." 1>&2
    exit 1
fi

ls "$1" 2>/dev/null 1>/dev/null
if [ $? -ne 0 ]; then
    echo "File doesn't exist." 1>&2
    exit 1
fi

digital='^[0-9]+$'
if ! [[ "$2" =~ $digital ]]; then
    echo "Please give: file name, partition number." 1>&2
    exit 1
fi

OFF_SECTORS=$(sudo parted -s $1 unit s print | tr -s " " | grep -P "^ $2" | cut -d ' ' -f 3 | perl -pe 's/s//g')
if [ -z "$OFF_SECTORS" ]; then
    echo "Wrong (non-existent) partition number."
    exit 1
fi
OFF_BYTES=$(echo "$OFF_SECTORS * 512" | bc -l)
sudo mount -o loop,offset=$OFF_BYTES "$1" /usr/local/mnt && echo -ne "Mounted partition number:\n\t$2\nfrom file:\n\t$1\nunder:\n\t/usr/local/mnt\n"
